export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';

export const STORE_GAME_HAS_STARTED = 'STORE_GAME_HAS_STARTED';

export const GO_TO_NEXT_QUESTION = 'GO_TO_NEXT_QUESTION';

export const STORE_CURRENT_QUESTION = 'STORE_CURRENT_QUESTION';
export const RESET_CURRENT_QUESTION = 'RESET_CURRENT_QUESTION';
